# Generated by Django 3.2.13 on 2022-07-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15, unique=True)),
                ('size', models.IntegerField()),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
