# Generated by Django 3.2.13 on 2022-07-05 19:51

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='admin', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('weight', models.FloatField()),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_restricted', models.BooleanField(default=False)),
                ('image_added', models.BooleanField(default=False)),
                ('delete_product', models.BooleanField(default=False)),
                ('main_video', models.FileField(blank=True, max_length=255, null=True, upload_to='images')),
                ('main_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images')),
                ('main_image_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='images')),
                ('main_image_small_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to='accounts.profile')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-date_created',),
            },
        ),
    ]
